name: Build Whisper Binary

on:
  workflow_dispatch: # Allow manual trigger
  push:
    paths:
      - '.github/workflows/build-whisper.yml'

jobs:
  build-whisper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Clone whisper.cpp
      run: |
        git clone https://github.com/ggerganov/whisper.cpp.git
        
    - name: Build whisper.cpp
      run: |
        cd whisper.cpp
        # Follow the official build instructions
        cmake -B build
        cmake --build build --config Release
        
    - name: Prepare binary
      run: |
        mkdir -p artifacts
        # Check what files were built and their sizes
        echo "=== Listing all built executables ==="
        find whisper.cpp/build -name "*" -type f -executable 2>/dev/null | head -20
        find whisper.cpp/build -name "*" -type f | grep -E "(main|whisper)" | head -20
        
        echo "=== File sizes ==="
        ls -la whisper.cpp/build/bin/ || true
        
        # The actual whisper binary should be much larger than 20KB
        # Let's try different locations for the main whisper binary
        WHISPER_BINARY=""
        
        # Check for the actual transcription binary (should be large, >1MB)
        # According to whisper.cpp docs, the main binary is whisper-cli in build/bin/
        for candidate in "whisper.cpp/build/bin/whisper-cli" "whisper.cpp/build/bin/main" "whisper.cpp/main" "whisper.cpp/build/examples/main"; do
          if [ -f "$candidate" ]; then
            size=$(stat -c%s "$candidate" 2>/dev/null || stat -f%z "$candidate" 2>/dev/null || echo "0")
            echo "Found $candidate with size $size bytes"
            if [ "$size" -gt 100000 ]; then  # Should be > 100KB for real whisper
              WHISPER_BINARY="$candidate"
              break
            fi
          fi
        done
        
        if [ -n "$WHISPER_BINARY" ]; then
          echo "Using whisper binary: $WHISPER_BINARY"
          cp "$WHISPER_BINARY" artifacts/whisper
          chmod +x artifacts/whisper
        else
          echo "ERROR: Could not find a suitable whisper binary!"
          echo "Available files:"
          find whisper.cpp/build -type f | head -30
          exit 1
        fi
        
    - name: Check binary info
      run: |
        file artifacts/whisper
        ldd artifacts/whisper || true
        
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: whisper-linux-x64
        path: artifacts/whisper
        retention-days: 30 