name: Build Whisper Binary

on:
  workflow_dispatch: # Allow manual trigger
  push:
    paths:
      - '.github/workflows/build-whisper.yml'

jobs:
  build-whisper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Clone whisper.cpp
      run: |
        git clone https://github.com/ggerganov/whisper.cpp.git
        
    - name: Build whisper.cpp
      run: |
        cd whisper.cpp
        make
        
    - name: Prepare binary
      run: |
        mkdir -p artifacts
        cp whisper.cpp/main artifacts/whisper
        chmod +x artifacts/whisper
        
    - name: Check binary info
      run: |
        file artifacts/whisper
        ldd artifacts/whisper || true
        
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: whisper-linux-x64
        path: artifacts/whisper
        retention-days: 30 