name: Build Whisper Binary

on:
  workflow_dispatch: # Allow manual trigger
  push:
    paths:
      - '.github/workflows/build-whisper.yml'

jobs:
  build-whisper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Clone whisper.cpp
      run: |
        git clone https://github.com/ggerganov/whisper.cpp.git
        
    - name: Build whisper.cpp
      run: |
        cd whisper.cpp
        make
        
    - name: Prepare binary
      run: |
        mkdir -p artifacts
        # Check what files were built
        find whisper.cpp -name "*main*" -type f || true
        find whisper.cpp -name "whisper*" -type f || true
        find whisper.cpp/build -name "*" -type f || true
        # Copy the correct binary (newer whisper.cpp builds put it in build/bin/)
        # We want the 'main' binary (which is the actual transcriber), not 'whisper-cli' (deprecated)
        if [ -f "whisper.cpp/build/bin/main" ]; then
          cp whisper.cpp/build/bin/main artifacts/whisper
        elif [ -f "whisper.cpp/main" ]; then
          cp whisper.cpp/main artifacts/whisper
        else
          echo "Could not find main whisper binary!"
          find whisper.cpp -name "*main*" -type f
          find whisper.cpp/build -name "*" -type f | head -20
          exit 1
        fi
        chmod +x artifacts/whisper
        
    - name: Check binary info
      run: |
        file artifacts/whisper
        ldd artifacts/whisper || true
        
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: whisper-linux-x64
        path: artifacts/whisper
        retention-days: 30 